### ISSUE TITLE
Duplicate work

### ISSUE THREAD

**Issue by DeltaEvo** [onivim/css-language-server#1]
I have done the same work as you https://github.com/vscode-langservers/vscode-css-languageserver-bin ❤️ 
I'm here to ask if there is a way to merge our two projects ?

**Comment by bryphe** [comment]
Hi @DeltaEvo ,

Thanks for reaching out! I didn't know about your project - looks like you're doing great work:
https://github.com/vscode-langservers

It's awesome that you've also extracted out the HTML and JSON language servers. I like that you split the implementation and `bin` commands too.

Your implementation of the CSS language server seems further along, so I'd be happy to deprecate this project in favor of yours. I'll just test it with [Oni](https://github.com/onivim/oni) once I'm back from vacation, and if everything looks good, I'll add a deprecation notice here and direct users to your repo. I can also open a PR on [https://github.com/langserver/langserver.github.io](langserver.org) to point to your implementation as opposed to this one.

Looking forward to testing out the HTML and JSON language servers. Thanks again for reaching out and saving us from duplicate work! 💯

**Comment by bryphe** [comment]
FYI - I tested out `vscode-css-languageserver-bin` and it works great with Oni. It's awesome having the diagnostics support.

I added a deprecation notice here, and sent a PR here: https://github.com/langserver/langserver.github.io/pull/70 to update https://langserver.org.

I'll close this out now, but let me know if there is anything else I can do here. Thanks @DeltaEvo !
